### PR TITLE
Setup/rearrange

### PR DESCRIPTION
**Pull request by Faxn**
I know I said the opposite when asked before, but I didn't quite understand what you meant when we talked about the client directory being inside the server directory. This pr moves the client directory next to the server directory and unites them with a top level package.json.

I also added a utility called subpackage which will run npm install on the client and server(and later the bot) after running npm install on the top level which makes setup somewhat easier. 

Finally I added some code to pull a message from the server and display it in the client. The existing code already made a request, but I wanted to be sure that data was getting across so I expanded it a bit.

### CODE REVIEW

**Comment by aaronmassey45** [comment]
Got it up and running! I'm good with rearranged the file structure. I had already checked to make sure the proxy was working, that's why I had that fetch in component did mount.

What's the benefit to using subpackage instead of writing our own script?
Top level "start" script shouldn't run "dev". When we deploy we aren't going to need the client server.

**Comment by Faxn** [comment]
I knew you were checking the fetch to the server, I just didn't trust that the promise not throwing an error meant that the data got across correctly so I expanded it a little. 

I can rip out subpackage if it matters to you. I installed it expecting it to do more than it does.

'start' running 'dev' was intended to be temporary. It will be changed when a working production deploy is set up. Since this seems to bother you I'll change it to just launch server like it did before.

**Comment by aaronmassey45** [comment]
I have nothing against what you've done, I'm just asking why and providing alternative solutions.

Even if the start script was temp, it's just a script that calls a script that calls two more scripts so why not eliminate a step and already have that ready for production? It doesn't "seem to bother me". If you know something that I don't just explain. It's a team effort.

I'm good with this PR.

**Review by aaronmassey45 — APPROVED** [review]

**Review by serjt12 — APPROVED** [review]

**Comment by aaronmassey45** [comment]
Some merge conflicts with .gitignore. We need to decide now if we are going dotenv or the other method so we can resolve and move on.

**Comment by Faxn** [comment]
I thought that decision was made when that branch was merged. Merging and closing.

**Pull request merged**
