### PR TITLE
Mongodb

### LINKED ISSUE #12: Mongo Set Up

### PR DESCRIPTION
**Pull request by serjt12**
mongo db set up
resolves #12

### CODE REVIEW

**Review by aaronmassey45 — CHANGES_REQUESTED** [review]
We can't have our keys exposed either we need to use dotenv or the method from my PR. 
The content in package.json in server should merge with the top level one.
I think you should add a console log or something just to make sure we are connected to db.
Do we need subPackages in package.json if subpkg has been removed? Or are we still going to use that?
Also we have some merge conflicts.

**Review by Faxn — CHANGES_REQUESTED** [review]
The subpackage key in /package.json is unused now, but removing it shouldn't be a requirement for acceptance of this pr, it's an unrelated thing. 

I think rebasing this to current development would fix most of the merge conflicts.

I second Aaron, the mongo uri should be taken from an environment variable, regardless of how it gets into that environment variable. It's deployment specific config so it shouldn't live in the repo.

**Comment by aaronmassey45** [comment]
@serjt12 I posted in slack with how to update to remove the sensitive data. You should also create a new username/password for the collection and delete the one with the info displayed here.

@Faxn I didn't say removing subPackage was a requirement. I was genuinely asking if it was still going to be used later. That being said, I don't think it's so difficult that it can not be done in this PR.

**Comment by Faxn** [comment]
resolves #12

**Review by Faxn — APPROVED** [review]

**Review by Faxn — CHANGES_REQUESTED** [review]
.gitignore and server/pakage.json have lines that seem to be from gits merge conflict tool. They need to be removed.

**Comment by aaronmassey45** [comment]
@serjt12 There are some git messages in index.js and package.json. Remove those and it should be good!

**Review by Faxn — APPROVED** [review]

**Pull request merged**
